#!/bin/sh
echo "This is a test"


sed -i -e '/squashfs/D' /var/lib/dpkg/info/linux-image-2.6.23-486-voyage.list 

KERNEL_VER=2.6.23-486-voyage
MODULE_IMAGE=squashfs-modules-"$KERNEL_VER" 

apt-get --yes --force-yes install $MODULE_IMAGE		

/usr/local/sbin/remove.docs

