#!/bin/sh

sed -i -e "s/ath/Ath/" /etc/udev/rules.d/*_persistent-net-generator.rules

# the workaround 
rm -f /etc/udev/rules.d/*persistent-net.rules
rm -f /etc/udev/rules.d/*persistent-net-generator.rules

######################################

rm -f /dev/*
mknod /dev/console c 5 1
mknod /dev/null c 1 3

