#!/bin/sh

echo -n "Installing /ro and /rw directories ... "
mkdir /rw /ro ro/dev ro/etc ro/usr ro/var
mv /root /ro/
ln -sf /rw/root /root
mv /tmp /ro/
ln -sf /rw/tmp /tmp
echo "Done"

#################################
# Remapping files to /rw
#################################
echo -n "Remapping files to /rw ... "
FILES="/etc/adjtime /etc/hostname /etc/issue /etc/issue.net /etc/resolv.conf /etc/mtab~"
FILES=$FILES" /var/lock /var/log /var/mail /var/run /var/spool /var/tmp /var/lib/dhcp"

for FILE in $FILES
do
	if [ ! -f $DEST/$FILE ] ; then touch $DEST/$FILE ; fi
	mv $FILE /ro/`dirname $FILE`
	ln -sf /rw$FILE $FILE
done
echo "Done"	

#################################
# Modifying /etc/network/ifstate
#################################
echo -n "Modifying /etc/network/run/ifstate ... "

ln -sf /rw/etc/network/run/ifstate /etc/network/run/ifstate
mkdir -p /ro/etc/network/run
touch /ro/etc/network/run/ifstate
echo "Done"
