#!/bin/sh

sed -i -e "s/ath/Ath/" /etc/udev/rules.d/z45_persistent-net-generator.rules

# the workaround 
rm -f /etc/udev/rules.d/z25_persistent-net.rules
rm -f /etc/udev/rules.d/z45_persistent-net-generator.rules

rm -rf /dev/*
mknod /dev/console c 5 1
mknod /dev/null c 1 3

