Document: voyage-util
Title: Debian voyage-util Manual
Author: <insert document author here>
Abstract: This manual describes what voyage-util is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/voyage-util/voyage-util.sgml.gz

Format: postscript
Files: /usr/share/doc/voyage-util/voyage-util.ps.gz

Format: text
Files: /usr/share/doc/voyage-util/voyage-util.text.gz

Format: HTML
Index: /usr/share/doc/voyage-util/html/index.html
Files: /usr/share/doc/voyage-util/html/*.html

  
