#!/bin/sh

cat << EOF > /etc/casper.conf
export USERNAME=""
export USERFULLNAME=""
export HOST="voyage"
export quite="n"
EOF


if [ -f /usr/share/initramfs-tools/hooks/casper ] ; then
cat << EOF >> /usr/share/initramfs-tools/hooks/casper

cp /etc/casper.conf \$DESTDIR/etc/
EOF
fi


CASPERDIR=/usr/share/initramfs-tools/scripts/casper-bottom

if [ -d $CASPERDIR ] ; then
#disable casper init scripts
chmod -x $CASPERDIR/??adduser
chmod -x $CASPERDIR/??networking
chmod -x $CASPERDIR/??autologin
chmod -x $CASPERDIR/??accessibility
chmod -x $CASPERDIR/??gnome_panel_data
fi


#patch initramfs nfs scripts
sed -i -e "s/nfsmount -o/mount -t nfs -o/" /usr/share/initramfs-tools/scripts/nfs

dpkg-reconfigure `dpkg-query --show | grep linux-image | tr -s "\t" " " | cut -d " " -f 1 `

